# @package _global_
defaults:
 - override /task: qm9_3d_noh
 - override /logger: wandb
 - override /method: midi
 - override /method/trainer: molecular_trainer
 - override /method/dataloader: [base_dataloader, batch_1024, workers_8]
 - override /method/callbacks: ckpt_orig_midi

method:
    trainer:
        max_epochs: 1000
        log_every_n_steps: 400
    model:
        params:
            cfg:
                model:
                    batch_size: 1024
                    n_layers: 10
                    lambda_train: [5, 0.4, 1, 2, 0]
            validation:
                how_many_to_generate: 1024

task:
    test:
        molecular:
            how_many_to_generate: 1024

logger:
    WandbLogger:
        project: d4-generation
        group: qm9-midi

config_name: qm9-midi-orig-noh


mode: train+eval
compile: true