# @package _global_
defaults:
 - override /method/model/architecture@method.model.params.denoising.architecture: graph_transformer/gt_large_distance_orig
 - override /task: gdb13_3d_mmff
 - override /task/test: molecular_3d_pre
 - override /logger: wandb
 - override /method: d4
 - override /method/trainer: molecular_trainer_gdb13
 - override /method/dataloader: [base_dataloader, batch_1536, workers_8]
 - override /method/callbacks: ckpt_ema_dist

method:
    model:
        params:
            generation:
                batch_size: 1536
            validation:
                how_many_to_generate: 1536
            embed_time: true
            features:
                - indegree
                - nodes_num
                - spectral
                - eigen_distance
            denoising:
                distance_output_mode: conditional
                #distance_output_mode: single
                loss:
                    lambda_train_X: 1.0
                    lambda_train_C: 1.0
                    lambda_train_E: 2.0
                    lambda_train_D: 4.0
                    lambda_eigenvalues_regularization: 1.0
    trainer:
        log_every_n_steps: 400
        gradient_clip_val: 1.0
    
    callbacks:
        early_stopping:
            EarlyStopping:
                patience: 30

logger:
    WandbLogger:
        project: d4-hparams
        group: gdb13-d4-mmff

config_name: gdb13-d4-mmff

mode: train+eval
compile: true
seed: 0