# @package _global_
defaults:
 - ../base
 - override /task: gdb13_3d
 - override /method/trainer: molecular_trainer_gdb13
 - override /method/dataloader: [base_dataloader, batch_1536, workers_8]
 - override /method/callbacks: ckpt_ema_dist

method:
    model:
        params:
            generation:
                batch_size: 1024
            validation:
                how_many_to_generate: 1024

logger:
    WandbLogger:
        project: d4-hparams
        group: gdb13-d4

config_name: gdb13-d4

mode: train+eval
compile: true
seed: 0