# @package _global_
defaults:
 - override /method/model/architecture@method.model.params.denoising.architecture: graph_transformer/gt_large_distance_orig_qm9
 - override /task: molecular_3d_pre
 - override /logger: wandb
 - override /method: d4
 - override /method/trainer: molecular_trainer
 - override /method/dataloader: [base_dataloader, batch_1024, workers_8]
 - override /method/callbacks: ckpt_orig_d4

method:
    model:
        params:
            generation:
                batch_size: 1024
            validation:
                how_many_to_generate: 1024

            embed_time: true
            features:
                - eigen_distance
            denoising:
                loss:
                    lambda_train_X: 1.0
                    lambda_train_C: 1.0
                    lambda_train_E: 2.0
                    lambda_train_D: 1.0
    trainer:
        log_every_n_steps: 400
        #gradient_clip_val: 1.0

task:
    test:
        molecular:
            how_many_to_generate: 1024

logger:
    WandbLogger:
        project: d4-generation
        group: qm9-d4

config_name: qm9-d4-orig


mode: train+eval
compile: true