# @package _global_
defaults:
 - override /task: qm9_3d
 - override /logger: wandb
 - override /platform: distributed_1gpu
 - override /method: dummy
 - override /method/trainer: molecular_trainer
 - override /method/dataloader: [single_graph]
 - override /method/callbacks: ckpt_ema_bond_dist

method:
    trainer:
        max_epochs: 2
        log_every_n_steps: 400
        check_val_every_n_epoch: 10
        gradient_clip_val: 1.0
    
    callbacks:
        early_stopping:
            EarlyStopping:
                patience: 20
    model:
        params:
            cfg:
                model:
                    batch_size: 1
            validation:
                how_many_to_generate: 1024

logger:
    WandbLogger:
        project: d4-generation
        group: qm9-dummy

config_name: qm9-dummy


mode: train+eval
compile: false
debug: true