# @package _global_
defaults:
 - ../base
 - override /task: zinc_3d
 - override /method/trainer: molecular_trainer_zinc
 - override /method/dataloader: [base_dataloader, batch_192, workers_8]
 - override /method/callbacks: ckpt_ema_dist

method:
    model:
        params:
            generation:
                batch_size: 192
            validation:
                how_many_to_generate: 192

logger:
    WandbLogger:
        project: d4-hparams
        group: zinc-d4

config_name: zinc-d4  

mode: train+eval
compile: false
seed: 0