name: zinc250k
params:
    random_splits:
        train: null
        valid: 0.16 # 0.8 * 0.2
        # test is predefined
    include_pos: true
    include_charges: true
    sanitize: false
    kekulize: true
    remove_hydrogens: true
    hard_remove_hydrogens: false
    num_workers: 8
    chunksize: 2000