defaults:
  - _self_
  - diffusion: marginal_500
  - /method/model/architecture@denoising.architecture: graph_transformer/gt_large_distance_orig
#  - ../architecture@denoising.architecture: graph_transformer/gt_large_distance_orig_qm9_copy
#  - ../architecture@denoising.architecture: graph_transformer/gt_large_distance_orig_qm9
#  - ../architecture: graph_transformer/gt_large_distance_orig


optimizer:
    lr: 0.0002
    weight_decay: 1.0e-12

denoising:
    loss:
        lambda_train_X: 0.4
        lambda_train_C: 1.0
        lambda_train_E: 2.0
        lambda_train_D: 4.0

generation:
    conditional: false
    batch_size: 256

validation:
    do_assignment: true
    how_many_to_generate: 256

features:
    - indegree