# @package _global_
defaults:
 - ./base


method:
    model:
        params:
            denoising:
                distance_output_mode: conditional
                loss:
                    lambda_eigenvalues_regularization: 1.0


config_name: qm9-d4-yesgradclip-lambda_d4


mode: train+eval
compile: false
seed: 0