# @package _global_
defaults:
 - ./best

method:
    model:
        params:
            denoising:
                distance_output_mode: single
                loss:
                    lambda_eigenvalues_regularization: 1.0


config_name: qm9-d4-no-conditional


mode: train+eval
compile: true
seed: 0