# @package _global_
defaults:
 - ./base

method:
    model:
        params:
            denoising:
                distance_output_mode: single
                loss:
                    lambda_eigenvalues_regularization: 0.0


config_name: qm9-d4-no-conditional-eig


mode: train+eval
compile: true
seed: 0