# @package _global_
defaults:
 - ../base
 - override /task: geom_drugs_3d
 - override /method/trainer: molecular_trainer_geom_drugs
 - override /method/dataloader: [base_dataloader, batch_1536, workers_8]
 - override /method/callbacks: ckpt_ema_dist

method:
    model:
        params:
            generation:
                batch_size: 1536
            validation:
                how_many_to_generate: 1536

logger:
    WandbLogger:
        project: d4-hparams
        group: geom-drugs-d4

config_name: geom-drugs-d4

mode: train+eval
compile: false
seed: 0